# Generated by Django 6.0.5 on 2026-05-10 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('clients', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], default='OPEN', max_length=30)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='assets.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to='organizations.organizationmembership')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='organizations.organization')),
                ('requested_by_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_work_orders', to='clients.clientcontact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='work_order_attachments/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Image'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('is_internal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_updates', to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'status'], name='workorders__organiz_90137b_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['organization', 'priority'], name='workorders__organiz_8aca80_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['client', 'status'], name='workorders__client__3788c0_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['assigned_to', 'status'], name='workorders__assigne_598c53_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['due_date'], name='workorders__due_dat_e8c492_idx'),
        ),
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['work_order', 'file_type'], name='workorders__work_or_528396_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderupdate',
            index=models.Index(fields=['work_order', 'created_at'], name='workorders__work_or_fe8b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='workorderupdate',
            index=models.Index(fields=['is_internal'], name='workorders__is_inte_09ec3c_idx'),
        ),
    ]
