# Generated by Django 6.0.5 on 2026-05-10 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderupdate',
            name='new_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workorderupdate',
            name='old_status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('OVERDUE', 'Overdue')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='workorderupdate',
            index=models.Index(fields=['user', 'created_at'], name='workorders__user_id_3ef1ae_idx'),
        ),
    ]
