services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
      - redis

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: maintolio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A config worker -l info
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
    volumes:
      - .:/app
    depends_on:
      - web
      - db
      - rabbitmq
      - redis

  celery_beat:
    build: .
    command: celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    environment:
      DB_HOST: db
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      REDIS_CACHE_URL: redis://redis:6379/1
    volumes:
      - .:/app
    depends_on:
      - web
      - db
      - rabbitmq
      - redis

volumes:
  postgres_data:
