# Generated by Django 6.0.5 on 2026-05-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('RETIRED', 'Retired')], default='ACTIVE', max_length=30)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='clients.client')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['client', 'status'], name='assets_asse_client__f19e7a_idx'), models.Index(fields=['serial_number'], name='assets_asse_serial__401a52_idx'), models.Index(fields=['asset_type'], name='assets_asse_asset_t_529092_idx')],
                'constraints': [models.UniqueConstraint(fields=('client', 'serial_number'), name='unique_asset_serial_per_client')],
            },
        ),
    ]
