# Generated by Django 6.0.5 on 2026-05-12 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organizations.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('can_login', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_contact_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['client__name', 'full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['organization', 'is_active'], name='clients_cli_organiz_c7479f_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='clients_cli_name_5ab7bc_idx'),
        ),
        migrations.AddConstraint(
            model_name='client',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_client_name_per_organization'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['client', 'is_active'], name='clients_cli_client__775a41_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['email'], name='clients_cli_email_030d36_idx'),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['can_login'], name='clients_cli_can_log_efde4d_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcontact',
            constraint=models.UniqueConstraint(fields=('client', 'email'), name='unique_contact_email_per_client'),
        ),
    ]
