# Generated by Django 6.0.5 on 2026-05-10 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='clientcontact',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='clientcontact',
            index=models.Index(fields=['can_login'], name='clients_cli_can_log_efde4d_idx'),
        ),
    ]
