# Generated by Django 6.0.5 on 2026-05-10 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('total_work_orders', models.PositiveIntegerField(default=0)),
                ('open_work_orders', models.PositiveIntegerField(default=0)),
                ('assigned_work_orders', models.PositiveIntegerField(default=0)),
                ('in_progress_work_orders', models.PositiveIntegerField(default=0)),
                ('on_hold_work_orders', models.PositiveIntegerField(default=0)),
                ('completed_work_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_work_orders', models.PositiveIntegerField(default=0)),
                ('overdue_work_orders', models.PositiveIntegerField(default=0)),
                ('urgent_work_orders', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_order_summaries', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'Daily work order summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='reports_dai_organiz_03fbab_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'date'), name='unique_daily_summary_per_organization')],
            },
        ),
    ]
