# Generated by Django 6.0.5 on 2026-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('total_work_orders', models.PositiveIntegerField(default=0)),
                ('open_work_orders', models.PositiveIntegerField(default=0)),
                ('assigned_work_orders', models.PositiveIntegerField(default=0)),
                ('in_progress_work_orders', models.PositiveIntegerField(default=0)),
                ('on_hold_work_orders', models.PositiveIntegerField(default=0)),
                ('completed_work_orders', models.PositiveIntegerField(default=0)),
                ('cancelled_work_orders', models.PositiveIntegerField(default=0)),
                ('overdue_work_orders', models.PositiveIntegerField(default=0)),
                ('urgent_work_orders', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Daily work order summaries',
                'ordering': ['-date'],
            },
        ),
    ]
